name: Docker CI

on:
  push:
    branches: 'main'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t evolving-creatures-app .

      - name: Lint with flake8 inside Docker container
        run: docker run evolving-creatures-app flake8

      - name: Check formatting with black inside Docker container
        run: docker run evolving-creatures-app black --check .

      - name: Run unittests inside Docker container
        run: docker run evolving-creatures-app python -m unittest discover

      # Ensure the context is the same as in pending-status.yml
      - name: Set Status to Success
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success',
              description: 'Checks passed',
              context: 'CI' # Set the context to the same name as in pending-status.yml
            })
