name: Docker CI

on:
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t evolving-creatures-app .

      - name: Lint with flake8 inside Docker container
        run: docker run evolving-creatures-app flake8

      - name: Check formatting with black inside Docker container
        run: docker run evolving-creatures-app black --check .

      - name: Run unittests inside Docker container
        run: docker run evolving-creatures-app python -m unittest discover
